[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
valapkg = { path = "." }

[tasks]
cli = "valapkg"

[package]
name = "valapkg"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }